# Generated by Django 5.0.4 on 2024-04-11 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmpID",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("emp_id", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=100, null=True)),
                ("lastName", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(max_length=100, null=True)),
                ("mobileNumber", models.CharField(max_length=15, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=False)),
                (
                    "emp_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.empid"
                    ),
                ),
            ],
        ),
    ]
