# Generated by Django 5.0.3 on 2024-04-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
            ('users', '0004_empmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('moduleName', models.CharField(max_length=100, null=True)),
                ('moduleKey', models.TextField()),
            ],
        ),
    ]
