# Generated by Django 5.0.4 on 2024-05-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_empmodule'),
        ('users', '0003_user_emp'),
    ]

    operations = [
    ]
