# Generated by Django 5.0.4 on 2024-05-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_empmodule'),
        ('users', '0003_user_emp'),
    ]

    operations = [
    ]
