# Generated by Django 5.0.4 on 2024-05-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0003_empmodule_0003_user_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
