# Generated by Django 5.0.4 on 2024-05-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0003_empmodule_0003_user_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emp',
        ),
    ]
