# Generated by Django 5.0.4 on 2024-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobileNumber',
            field=models.BigIntegerField(),
        ),
    ]
