# Generated by Django 5.0.4 on 2024-05-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_mobilenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emp',
        ),
    ]
