# Generated by Django 5.0.4 on 2024-05-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_emp'),
        ('users', '0019_user_emp'),
    ]

    operations = [
    ]
