# Generated by Django 5.0.4 on 2024-05-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_0006_user_emp_0019_user_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empid',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
