# Generated by Django 5.0.4 on 2024-05-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_empid_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
