# Generated by Django 5.0.4 on 2024-05-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empmodule',
            name='moduleKey',
        ),
    ]
