# Generated by Django 5.0.3 on 2024-04-17 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_details', models.TextField(max_length=100)),
                ('feedback_provider', models.CharField(max_length=30)),
                ('feedback_rating', models.IntegerField(blank=True, null=True)),
                ('feedback_date', models.DateField()),
                ('publish', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
