# Generated by Django 5.0.4 on 2024-05-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
