# Generated by Django 5.0.3 on 2024-04-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50)),
            ],
        ),
    ]
