# Generated by Django 5.0.3 on 2024-04-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_emprole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('streamName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500, unique=True)),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('correctAnswer', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('subjective', 'Subjective Question')], max_length=50)),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')])),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.stream')),
            ],
        ),
    ]
