# Generated by Django 5.0.3 on 2024-04-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_auto_20240416_1821'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currrentStatus', models.CharField(max_length=100)),
                ('round1', models.CharField(max_length=100)),
                ('round2', models.CharField(max_length=100)),
                ('round3', models.CharField(max_length=100)),
                ('round4', models.CharField(max_length=100)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
