# Generated by Django 5.0.3 on 2024-04-17 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_track'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduledDate', models.DateField()),
                ('status', models.TextField(choices=[(1, 'started'), (2, 'completed'), (3, 'todo'), (4, 'inprogress'), (5, 'disqualified')])),
                ('round', models.IntegerField(choices=[(1, 'Round 1'), (2, 'Round 2')])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
