# Generated by Django 5.0.3 on 2024-04-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0011_authorizationtomodule'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Hide', 'Hide'), ('InActive', 'InActive')], default='InActive', max_length=20)),
                ('jobName', models.CharField(max_length=100)),
                ('jobDescription', models.TextField()),
                ('jobSkills', models.TextField()),
                ('experience', models.IntegerField()),
                ('expire', models.DateField()),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
