# Generated by Django 5.0.3 on 2024-04-17 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0014_notification'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateUrl', models.URLField()),
                ('dateIssued', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.exam')),
            ],
        ),
    ]
