# Generated by Django 5.0.3 on 2024-04-23 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0015_certification'),
        ('users', '0002_alter_user_address_alter_user_cv_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
