# Generated by Django 5.0.4 on 2024-04-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0016_applyjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='jobId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='jobName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
