# Generated by Django 5.0.4 on 2024-04-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0017_notification_jobid_notification_jobname'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='currentStatus',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
