# Generated by Django 5.0.4 on 2024-04-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0018_notification_currentstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='currrentStatus',
            new_name='currentStatus',
        ),
    ]
