# Generated by Django 5.0.3 on 2024-04-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0016_questions_candidate'),
        ('recruit', '0019_rename_currrentstatus_track_currentstatus'),
    ]

    operations = [
    ]
