# Generated by Django 5.0.4 on 2024-05-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0020_merge_20240425_1557'),
        ('recruit', '0020_result_question_alter_result_scheduler'),
    ]

    operations = [
    ]
