# Generated by Django 5.0.4 on 2024-05-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0021_merge_20240502_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizeToModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empmodule')),
            ],
        ),
    ]
