# Generated by Django 5.0.4 on 2024-05-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0021_merge_20240502_1201'),
        ('recruit', '0022_authorizetomodule'),
    ]

    operations = [
    ]
