# Generated by Django 5.0.4 on 2024-05-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0024_questions_scheduler_alter_scheduler_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='scheduler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruit.scheduler'),
        ),
    ]
