# Generated by Django 5.0.4 on 2024-05-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0025_alter_questions_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
