# Generated by Django 5.0.4 on 2024-05-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0026_questions_option1_questions_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
