# Generated by Django 5.0.4 on 2024-05-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0027_questions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='scheduler',
        ),
        migrations.AlterField(
            model_name='questions',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
