# Generated by Django 5.0.4 on 2024-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0028_remove_questions_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationtoemployee',
            name='round',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='AuthorizationToModule',
        ),
    ]
