# Generated by Django 5.0.4 on 2024-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0029_authorizationtoemployee_round_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorizationtoemployee',
            old_name='emp',
            new_name='emp_id',
        ),
        migrations.RemoveField(
            model_name='authorizationtoemployee',
            name='candidate',
        ),
        migrations.AddField(
            model_name='authorizationtoemployee',
            name='candidate_id',
            field=models.IntegerField(null=True),
        ),
    ]
