# Generated by Django 5.0.4 on 2024-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0030_rename_emp_authorizationtoemployee_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationtoemployee',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
    ]
