# Generated by Django 5.0.4 on 2024-05-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0031_alter_authorizationtoemployee_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='jobID',
            new_name='jobId',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='appliedDate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='marks',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='passingYear',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='qualification',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='skills',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
