# Generated by Django 5.0.4 on 2024-05-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0033_remove_applyjob_applieddate_remove_applyjob_jobid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='marks',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
