# Generated by Django 5.0.4 on 2024-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0034_alter_applyjob_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
    ]
