# Generated by Django 5.0.4 on 2024-05-27 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0035_scheduler_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='job_id',
            new_name='application_id',
        ),
    ]
